name: shelf_web_socket
version: 0.2.1
author: "Dart Team <misc@dartlang.org>"
homepage: http://github.com/dart-lang/shelf_web_socket
description: >
  A WebSocket handler for Shelf.
dependencies:
  shelf: ">=0.6.5 <0.8.0"
  stream_channel: "^1.4.0"
  web_socket_channel: "^1.0.0"
dev_dependencies:
  http: ">=0.10.0 <0.12.0"
  test: "^0.12.0"
environment:
  sdk: ">=1.8.0 <2.0.0"
