name: shelf_static
version: 1.1.0
description: Static file server support for the shelf package and ecosystem
repository: https://github.com/dart-lang/shelf_static

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  convert: ^3.0.0
  http_parser: ^4.0.0
  mime: ^1.0.0
  path: ^1.8.0
  # shelf version that allows correctly setting content-length w/ HEAD
  shelf: ^1.1.2

dev_dependencies:
  args: ^2.0.0
  test: ^1.16.0
  test_descriptor: ^2.0.0
