name: shelf_proxy
version: 1.0.0
description: A shelf handler for proxying HTTP requests to another server.
repository: https://github.com/dart-lang/shelf_proxy

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  path: ^1.8.0
  pedantic: ^1.0.0
  shelf: ^1.0.0

dev_dependencies:
  test: ^1.6.0
