name: shelf
version: 0.7.1-dev
author: Dart Team <misc@dartlang.org>
description: Web Server Middleware for Dart
homepage: https://github.com/dart-lang/shelf
environment:
  sdk: '>=1.23.0 <2.0.0'
dependencies:
  async: '>=1.10.0 <3.0.0'
  collection: '^1.5.0'
  http_parser: '^3.1.0'
  path: '^1.0.0'
  stack_trace: '^1.0.0'
  stream_channel: '^1.0.0'
dev_dependencies:
  http: '>=0.9.2 <0.12.0'
  test: '^0.12.20'
