name: shelf
version: 0.7.4

description: Web Server Middleware for Dart
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/shelf

environment:
  sdk: '>=2.0.0-dev.61.0 <3.0.0'

dependencies:
  async: ^2.0.7
  collection: ^1.5.0
  http_parser: ^3.1.0
  path: ^1.0.0
  stack_trace: ^1.0.0
  stream_channel: ^1.0.0

dev_dependencies:
  http: ^0.11.3
  test: ^1.2.0
