name: shelf
version: 0.6.2-dev
author: Dart Team <misc@dartlang.org>
description: Web Server Middleware for Dart
homepage: https://github.com/dart-lang/shelf
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  collection: '^1.0.0'
  http_parser: '^0.0.0'
  path: '^1.0.0'
  stack_trace: '^1.0.0'
dev_dependencies:
  http: '>=0.9.2 <0.12.0'
  scheduled_test: '>=0.10.0 <0.12.0'
  unittest: '>=0.10.0 <0.12.0'
