name: shelf_proxy
version: 1.0.5-wip
description: A shelf handler for proxying HTTP requests to another server.
repository: https://github.com/dart-lang/shelf/tree/master/pkgs/shelf_proxy
issue_tracker: https://github.com/dart-lang/shelf/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Ashelf_proxy

topics:
  - server
  - shelf

environment:
  sdk: ^3.3.0

dependencies:
  http: '>=0.13.0 <2.0.0'
  path: ^1.8.0
  shelf: ^1.0.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.6.0
