name: shelf
version: 1.4.3-wip
description: >
  A model for web server middleware that encourages composition and easy reuse.
repository: https://github.com/dart-lang/shelf/tree/master/pkgs/shelf
issue_tracker: https://github.com/dart-lang/shelf/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Ashelf

topics:
  - server
  - shelf
  - backend

environment:
  sdk: ^3.4.0

dependencies:
  async: ^2.5.0
  collection: ^1.15.0
  http_parser: ^4.1.0
  path: ^1.8.0
  stack_trace: ^1.10.0
  stream_channel: ^2.1.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  http: '>=0.13.0 <2.0.0'
  test: ^1.16.0
