name: shelf_web_socket
version: 3.0.0-wip
description: A shelf handler that wires up a listener for every connection.
repository: https://github.com/dart-lang/shelf/tree/master/pkgs/shelf_web_socket
issue_tracker: https://github.com/dart-lang/shelf/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Ashelf_web_socket

topics:
  - server
  - shelf

environment:
  sdk: ^3.3.0

dependencies:
  shelf: ^1.1.0
  stream_channel: ^2.1.0
  web_socket_channel: '>=2.0.0 <4.0.0'

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  http: '>=0.13.0 <2.0.0'
  test: ^1.25.2

# TODO(devoncarew): Remove once package:test supports v2+v3 of shelf_web_socket.
dependency_overrides:
  test: ^1.25.11
