name: shelf_web_socket
version: 1.9.9-wip  # DO NOT SUBMIT! Should be 2.0.0-wip.
description: >
  A shelf handler that wires up a listener for every connection.
repository: https://github.com/dart-lang/shelf/tree/master/pkgs/shelf_web_socket

topics:
  - server
  - shelf

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.1.0
  stream_channel: ^2.1.0
  web_socket_channel: '>=2.0.0 <=4.0.0'

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
  http: '>=0.13.0 <2.0.0'
  test: ^1.16.0
