name: shelf_packages_handler
version: 3.0.3-wip
description: A shelf handler for serving a `packages/` directory.
repository: https://github.com/dart-lang/shelf/tree/master/pkgs/shelf_packages_handler
issue_tracker: https://github.com/dart-lang/shelf/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Ashelf_packages_handler

topics:
  - server
  - shelf

environment:
  sdk: ^3.3.0

dependencies:
  path: ^1.8.0
  shelf: ^1.0.0
  shelf_static: ^1.0.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.0
