name: shelf_router_generator
version: 1.1.3
description: >
  A package:build-compatible builder for generating request routers for the
  shelf web-framework based on source annotations.
repository: https://github.com/dart-lang/shelf/tree/master/pkgs/shelf_router_generator
issue_tracker: https://github.com/dart-lang/shelf/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Ashelf_router_generator

topics:
  - server
  - shelf

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ^8.1.1
  build: ^4.0.0
  build_config: ^1.2.0
  code_builder: ^4.2.0
  http_methods: ^1.1.0
  shelf: ^1.1.0
  shelf_router: ^1.1.0
  source_gen: ^4.0.1

dev_dependencies:
  build_runner: ^2.7.2
  build_verify: ^3.0.0
  dart_flutter_team_lints: ^3.0.0
  http: ^1.0.0
  test: ^1.26.3
