name: shelf_router_generator
version: 1.1.0
description: >
  A package:build-compatible builder for generating request routers for the
  shelf web-framework based on source annotations.
repository: https://github.com/dart-lang/shelf/tree/master/pkgs/shelf_router_generator

topics:
  - server
  - shelf

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: '>=4.6.0 <7.0.0'
  build: ^2.0.0
  build_config: ^1.0.0
  code_builder: ^4.2.0
  http_methods: ^1.0.0
  shelf: ^1.1.0
  shelf_router: ^1.1.0
  source_gen: ^1.0.0

dev_dependencies:
  args: ^2.0.0
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  dart_flutter_team_lints: ^2.0.0
  http: '>=0.13.0 <2.0.0'
  test: ^1.5.3
