name: shelf_router_generator
version: 1.0.1
description: >-
  A package:build compatible builder for generating request routers for the
  shelf web-framework based on source annotations.
homepage: https://github.com/google/dart-neats/tree/master/shelf_router_generator
repository: https://github.com/google/dart-neats.git
issue_tracker: https://github.com/google/dart-neats/labels/pkg:shelf_router_generator

dependencies:
  analyzer: '>=1.2.0 <3.0.0'
  build: ^2.0.0
  build_config: ^1.0.0
  code_builder: ^4.0.0
  http_methods: ^1.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^2.0.0
  http: ^0.13.0
  pedantic: ^1.4.0
  test: ^1.5.3

environment:
  sdk: '>=2.12.0 <3.0.0'
