name: shelf_router_generator
version: 0.7.0+1
authors:
  - Jonas Finnemann Jensen <jonasfj@google.com>
description: |
  A package:build compatible builder for generating request routers for the
  shelf web-framework based on source annotations.
homepage: https://github.com/google/dart-neats/tree/master/shelf_router_generator
repository: https://github.com/google/dart-neats.git
issue_tracker: https://github.com/google/dart-neats/labels/pkg:shelf_router_generator
dependencies:
  build: ^1.0.0
  build_config: ^0.3.1
  source_gen: ^0.9.1
  analyzer:  ^0.35.0
  shelf_router: ^0.7.0
  code_builder: ^3.2.0
  shelf: ^0.7.3
  meta: ^1.1.7
  http_methods: ^1.0.0
dev_dependencies:
  test: ^1.5.3
  http: ^0.12.0+1
  build_verify: ^1.1.1
  build_runner: ^1.2.8
  pedantic: ^1.4.0
environment:
  sdk: '>=2.0.0 <3.0.0'